---
name: Homebrew

on:
  pull_request: null
  push:
    branches:
      - master
  workflow_dispatch: null

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  style:
    name: Formula Style
    if: >-
      github.event_name != 'pull_request' ||
      contains(fromJSON('["OWNER", "MEMBER", "COLLABORATOR"]'), github.event.pull_request.author_association) ||
      (github.event.pull_request.user.type == 'Bot' &&
      contains(fromJSON('[29139614, 41898282, 49699333]'), github.event.pull_request.user.id))
    runs-on: macos-latest
    timeout-minutes: 15
    steps:
      - name: Checkout Repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Set Up Check Tools
        uses: ./.github/actions/setup-check-tools # zizmor: ignore[self-repository]

      - name: Install Homebrew RubyGems
        run: brew install-bundler-gems

      - name: Check Homebrew
        run: just homebrew-check
